FROM python:3.8-alpine

WORKDIR /app

COPY ./server_sqlite.py ./requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt



# Run app.py when the container launches
CMD ["uvicorn", "server_sqlite:app", "--host", "0.0.0.0", "--port", "8000"]